# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
# For more information, see: https://github.com/actions/stale
name: Track Stale Issues

on:
  schedule:
  - cron: '12 9 * * 4'

permissions: read-all

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
      with:
        days-before-stale: 350
        days-before-close: 50
        stale-issue-message: 'No activity with issue for 350 days.'
        stale-pr-message: 'No activity with pull request for 350 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        close-issue-message: 'No activity for 400 days.  Will not fix.'
        close-pr-message: 'No activity for 400 days.  Will not merge.'
        close-issue-label: 'wontfix'
        close-pr-label: 'wontfix'
